name: IPFS Remote Pinning
on: [push]
jobs:
  pin_to_ipfs:
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - uses: actions/checkout@v2
    - name: IPFS Publish
      id: IPFS
      uses: kelindi/estuary-upload-action@949545b85907cc4a81b5318b4077f0beb7ef3c11
      with:
        path_to_add: './fonts' #Required
        access_token: ${{ secrets.ACCESS_TOKEN }} #Required
 
