name: IPFS Remote Pinning
on: [push]
jobs:
  pin_to_ipfs:
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - uses: actions/checkout@v2
    - name: IPFS Publish
      id: IPFS
      uses: kelindi/estuary-upload-action@v0.1.1-alpha
      with:
        path_to_add: './' #Required
        access_token: ${{ secrets.ACCESS_TOKEN }} #Required
        pin_name: 'github-actions-test' #Optional
