name: IPFS Remote Pinning
on: [push]
jobs:
  pin_to_ipfs:
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - uses: actions/checkout@v2
    - name: IPFS Publish
      id: IPFS
      uses: kelindi/estuary-upload-action@c2f6d0cb3ac8aceb073cfc42e0b277c348aafe66
      with:
        path_to_add: './fonts' #Required
        access_token: ${{ secrets.ACCESS_TOKEN }} #Required
 
