name: IPFS Remote Pinning
on: [push]
jobs:
  pin_to_ipfs:
    runs-on: ubuntu-latest
    name: Publish
    steps:
    - uses: actions/checkout@v2
    - name: IPFS Publish
      id: IPFS
      uses: kelindi/estuary-upload-action@62a58017752d60f87078e7e23688be03cea90c
      with:
        path_to_add: './fonts' #Required
        access_token: ${{ secrets.ACCESS_TOKEN }} #Required
 
